name: test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
